#!/bin/bash
ARG1=$1
LIVE_SYNC_DIRECTORY="$HOME/Clockwork/live_sync/live_sync"
CWD=$(pwd)

if [ -n "$ARG1" ]
	then
	cp -a "$LIVE_SYNC_DIRECTORY" "$CWD/.live_sync"
	echo "$ARG1" > "$CWD/.live_sync/live_sync_remote"
	echo "Live Sync Setup"
	live_sync -p
	exit
fi

echo "You must provide the remote path"

